version: "3.3"
services:
  replica_test_service:
    build:
      context: .
    ports:
      - "1926:1926"
    networks:
      - network
    restart: always
    container_name: replica_test_service
    depends_on:
      - mongodb1
  mongodb1:
    image: mongo
    restart: always
    container_name: mongodb1
    volumes:
    - mongodata1:/data/db
    networks:
      - network
    ports:
      - "27001:27017"
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

  mongodb2:
    image: mongo
    restart: always
    networks:
      - network
    container_name: mongodb2
    volumes:
    - mongodata2:/data/db
    ports:
      - "27002:27017"
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

  mongodb3:
    image: mongo
    restart: always
    networks:
      - network
    container_name: mongodb3
    volumes:
    - mongodata3:/data/db
    ports:
      - "27003:27017"
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1" ]

  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    networks:
      - network
    container_name: mongosetup
    depends_on:
        - mongodb1
        - mongodb2
        - mongodb3
    volumes:
        - mongostatus:/data/

volumes:
    mongodata1:
    mongodata2:
    mongodata3:
    mongostatus:

networks:
  network:
